version: '3'
services:
  gcc:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "./build.sh && /bin/bash"
    stdin_open: true
    tty: true